### ISSUE TITLE
codecov Install/Setup

### ISSUE THREAD

**Issue by KjartanE** [SENG-499-Company-3/backend#28]
Ticket: Increase test coverage for API functions and integrate CodeCov with GitHub PR and Mocha

As a developer
I want to increase the test coverage for the API functions
So that I can ensure the reliability and quality of the code

Background:
- The project is hosted on GitHub
- Mocha is used as the testing framework
- CodeCov is not currently integrated with the project

Scenario: Integrate CodeCov with GitHub PR and Mocha
Given a GitHub repository with API functions implemented
And a Mocha test suite for API functions
And CodeCov is not integrated with the repository
When I integrate CodeCov with the repository
And configure it to run during pull requests
Then the test coverage report should be displayed on GitHub PRs
And a coverage threshold should be set for further improvements

**Comment by KjartanE** [comment]
SonarQube has a paywall for PR integration. Looking at other utilities for this requirement.

Possible solutions - (Mocha/Istanbul (NYC)/CodeCov):
https://www.testim.io/blog/mocha-code-coverage-how-to-use-instanbul-to-get-going/
https://medium.com/@bhindersx/code-coverage-reporting-in-javascript-with-istanbul-along-with-mocha-in-ci-process-7e923dc57455
https://github.com/dwyl/learn-istanbul

PR COMMENT WITH CODECOV:
https://docs.codecov.com/docs/pull-request-comments

**Comment by KjartanE** [comment]
Following the DOCs on the CodeCov webiste is pretty useful: https://docs.codecov.com/docs/github-tutorial

**Comment by MMojtaba** [comment]
Works using instanbul to generate coverage report, and codecov to upload the results to codecov website. The coverage is also seen in github when clicking the checkmark above the repository.

To change testing method (to mocha) change the test target in package.json
After testing it with this branch, can change the file codecov.yml in workflows folder to target dev and prod branches.

![Image](https://github.com/SENG-499-Company-3/backend/assets/44787178/f6285d75-0d7c-478e-8000-e78fe2f54c35)



![Image](https://github.com/SENG-499-Company-3/backend/assets/44787178/19c01c04-e33f-4d29-9bea-00dcac302d65)
