### ISSUE TITLE
Define and implement endpoint API request body restrictions

### ISSUE THREAD

**Issue by KjartanE** [SENG-499-Company-3/backend#44]
Ticket: Define and implement endpoint API request body restrictions

As a developer
I want to define and implement restrictions for the request body of an API endpoint
So that I can ensure the validity and security of incoming data

Scenario: Define request body restrictions for an API endpoint
Given an existing API endpoint named "/api/resource"
And the need to enforce specific restrictions on the request body
When I review the requirements and design specifications
And define the allowed data types, formats, and validation rules for each field in the request body
Then I should update the API documentation with the defined restrictions
And implement the necessary validation logic in the endpoint code
And test the endpoint with various valid and invalid request bodies to ensure the restrictions are enforced correctly

**Comment by Gavinok** [comment]
https://betterprogramming.pub/runtime-data-validation-from-typescript-interfaces-1001ad22e775

https://www.npmjs.com/package/openapi-typescript

**Comment by Gavinok** [comment]
https://www.npmjs.com/package/typescript-json-schema

**Comment by Gavinok** [comment]
we have 2 options so far can use `openapi-typescript` to generate an api for the openapi and use `typescript-json-schema` to generate a schema for it. Alternatively we can just use https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

**Comment by Gavinok** [comment]
https://www.npmjs.com/package/express-jsonschema we can use this with expressjs to validate these json-schemas
